### ISSUE TITLE
geocoder tester

### ISSUE THREAD

**Issue by nlehuby** [geometalab/Geocoder-Benchmark#1]
Do you now the [geocoder-tester project](https://github.com/geocoders/geocoder-tester) ?
It's a tool to run a list of geocoding queries and check the results against expected values (coordinates, but also labels or postalcodes).

It would be really great to have your test cases in geocoder tester ;)

**Comment by sfkeller** [comment]
Hi Noémi,

Thanks for your hint. 

No we didn't know this project - although I know Yohan. I'm also glad to see that Yohan was testing my other project OSMNames here https://github.com/geocoders/osmnames_geocodejson .

This "Geocoder-Benchmark" code was only a short experiment and the project/repo is currently not maintained actively. 

But since geocoders are changing all the time, we eventually will revive this "Geocoder-Benchmark" project - and then we'll check if your "geocoder-tester" project can be used.
